/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jason_nativeinterface_jni_CryptTool */

#ifndef _Included_com_jason_nativeinterface_jni_CryptTool
#define _Included_com_jason_nativeinterface_jni_CryptTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jason_nativeinterface_jni_CryptTool
 * Method:    getCryptKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jason_nativeinterface_jni_CryptTool_getCryptKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
